name: 'Dependency Review'

on: [ pull_request ]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          config-file: darbiadev/.github/.github/dependency-review-config.yaml@0c105e4ec7fd13ac581ccd1ea3fe5f25091ddc14
