name: "Docker Build and Push"

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio.
  id-token: write

jobs:
  build-push:
    uses: darbiadev/.github/.github/workflows/docker-build-push.yaml@9e24c0c311791b544f8e21a6d3f979ad1c89462c

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: "Update deployment"
        run: curl --fail-with-body -X POST '${{ secrets.DEPLOY_WEBHOOK }}'
