name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@1163b50ed46a8aea41806ee86ec2eb50605521ac

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@1163b50ed46a8aea41806ee86ec2eb50605521ac

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10", "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@1163b50ed46a8aea41806ee86ec2eb50605521ac
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
