name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@8209a320c942ec889f2f73752bebdcb2806792e5

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@8209a320c942ec889f2f73752bebdcb2806792e5

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10", "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@8209a320c942ec889f2f73752bebdcb2806792e5
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
